messages:
  prefix: '[Rankup]'
  no_perm: 'You don''t have permission to use this command!'
  already_highest: You have the highest available rank!
  next_rank: '&eThe next rank is &f{rank}&e, which price is: &a${price}'
  next_rank_noprice: '&eThe next rank is &f{rank}&e!'
  next_rank_diff: '&cYou need &a${diff} &cmore to get this rank!'
  transaction_error: An error occurred while processing your request! Please notify an Administrator!
  rank_buy_success: '&aYou successfully bought the &f{rank} &arank!'
  status:
    current_rank: '&dCurrent rank: &f{rank}&r'
    next_rank: '&dNext rank: &f{rank}&r'
  reloaded: Plugin reloaded!
  rank_changed: '&aYour rank successfully changed to &f{rank}&a!'
  rank_changed_other: '&c{player}''s &arank successfully changed to &f{rank}&a!'
  rank_not_found: 'This rank doesn''t exist!'
  getrank:
    same_rank: You already have this rank!
    bigger_rank: You already have a bigger rank!
    not_yet: 'You can''t buy this rank yet.'
    rank_diff: '&cYou need &a${diff} &cmore to get the &f{rank} &crank!'
  player_not_found: 'The specified player doesn''t exist OR does not have a rank!'
  other_player_rank: '&e{player}&d''s current rank: &f{rank}&d!'

ranks:
  '1':
    name: coal
    display: '&8Coal'
    priority: 1
    price: 100
  '2':
    name: iron
    display: '&7Iron'
    priority: 2
    price: 200
  '3':
    name: gold
    display: '&6Gold'
    priority: 3
    price: 300
  '4':
    name: diamond
    display: '&bDiamond'
    priority: 4
    price: 400
  '5':
    name: emerald
    display: '&aEmerald'
    priority: 5
    price: 500
  '6':
    name: default
    display: '&5None'
    priority: 0
    price: 0